version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    expose:
    - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mern-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      IP: mongo
